### ISSUE TITLE
Provide more instructions

### ISSUE THREAD

**Issue by fgionghi** [mattwparas/helix-config#1]
Hi! Thank you for your work, unfortunately I know nothing about steel or rust. 
Could you provide some instruction to be able to try this fork?
Thank you

**Comment by mattwparas** [comment]
Sorry for the delay, I've been under the weather the last few days so I haven't fully tested this end to end. Let me know if you run into any issues,

You'll have to do a few steps:

Clone the [steel](https://github.com/mattwparas/steel) repo and install it - the easiest way I think now is to first set the `STEEL_HOME` env var to somewhere on your machine, and then run `cargo xtask install`.

Then, clone my fork of helix found [here](https://github.com/mattwparas/helix/tree/steel-event-system). From the root of that, run `cargo xtask steel`.

Then, put this helix-config repo under `~/.config/helix`

**Comment by Boltzmachine** [comment]
Hi, may I ask which command give me `hx` executable since I did not get one by following the instructions in this thread

**Comment by mattwparas** [comment]
Have you cloned this repo? https://github.com/mattwparas/helix/tree/steel-event-system

If not, clone that, then run `cargo xtask steel` - it should do the proper helix installation

**Comment by Boltzmachine** [comment]
Thanks. I just found I was not on the right branch

**Comment by YanniPapandreou** [comment]
> Have you cloned this repo? https://github.com/mattwparas/helix/tree/steel-event-system
> 
> If not, clone that, then run `cargo xtask steel` - it should do the proper helix installation (since I posted that above, I've consolidated all of the instructions into one step)
> 
> If that still doesn't provide a `hx` executable, are the logs of the output any help? Maybe the helix install failed?

Sorry to open this again, but I was trying to follow this but the step `cargo xtask steel` fails with error:
```
Error: "Invalid task name: steel"
```
and I am unsure what the correct task name is, the help only suggests:
```
Usage: Run with `cargo xtask <task>`, eg. `cargo xtask docgen`.

    Tasks:
        docgen: Generate files to be included in the mdbook output.
        query-check: Check that tree-sitter queries are valid.
```
and neither name suggest they install helix?

P.s. thanks for the awesome work, I'm very excited to try this out.

**Comment by YanniPapandreou** [comment]
ahh please ignore, was also on wrong branch
