### ISSUE TITLE
File tree free identifier

### ISSUE THREAD

**Issue by mattwparas** [mattwparas/helix-config#3]
> This is how it works now, however it is subject to change as I work on improving the keybinding API:
> 
> ```scheme
> # helix.scm
> 
> ;;;;;;;;;;;;;;; File Tree ;;;;;;;;;;;;;;;;;
> 
> (require "cogs/file-tree.scm")
> 
> (provide fold-directory
>          unfold-all-one-level
>          open-file-from-picker
>          create-file-tree
>          create-file
>          create-directory
>          fold-all
>          FILE-TREE
>          FILE-TREE-KEYBINDINGS)
> ```
> 
> ```scheme
> # init.scm
> 
> (require (only-in "cogs/file-tree.scm" FILE-TREE-KEYBINDINGS FILE-TREE))
> (require "cogs/keymaps.scm")
> 
> (define file-tree-base (deep-copy-global-keybindings))
> 
> (merge-keybindings file-tree-base FILE-TREE-KEYBINDINGS)
> 
> ;; <scratch> + <doc id> is probably the best way to handle this?
> (set-global-buffer-or-extension-keymap (hash  FILE-TREE file-tree-base))
> ```

Ah i see. This is 100% out the scope of the plugin system itself and more related to that particular plugin but i get errors with the current example:

```file-tree.scm
 error[E02]: FreeIdentifier
      ┌─ /Users/{path}/.config/helix/cogs/file-tree.scm:92:36
      │
   92 │   (set! *directories* (hash-insert *directories* directory #t)))
      │                                    ^^^^^^^^^^^^^ *directories*
```

_Originally posted by @peteringram0 in https://github.com/mattwparas/helix-config/issues/2#issuecomment-2211836229_

**Comment by mattwparas** [comment]
Have you made any changes to the source code?

**Comment by mattwparas** [comment]
Okay, I'm unable to reproduce this even with a fresh install of helix on the latest branch: `steel-event-system` - do  you have the full cogs directory from this repo?

Free identifier is a strange error to see since it is there on line 88 - if you can provide your exact init.scm and helix.scm files I can try to reproduce it

**Comment by mattwparas** [comment]
Hey @peteringram0 just checking, is this still occurring? I ran through the whole install on a fresh machine and wasn't able to reproduce

**Comment by peteringram0** [comment]
> Hey @peteringram0 just checking, is this still occurring? I ran through the whole install on a fresh machine and wasn't able to reproduce

@mattwparas sorry I think this was a PICNIC issue. It's not throwing any issues however I'm not actually sure how to use it (maybe there is a config value I need to activate or something) there are some keybindings listed which don't seem to work (maybe my environment setup). I can run the 'generate tree' command and seems to output some text but I expected it to be an interactive tree I could use to load files into the buffer. Most likely this is a skill or understanding issue. Thank you for your hard work on this plugin system!

**Comment by mattwparas** [comment]
So it is an interactive buffer - to give some guidance since there is no documentation:

```
:create-file-tree - opens the file tree buffer
```

Once you're in that buffer, you should be able to navigate like usual. `tab` should fold/unfold a directory, `o` should open that file into a buffer

**Comment by peteringram0** [comment]
> So it is an interactive buffer - to give some guidance since there is no documentation:
> 
> ```
> :create-file-tree - opens the file tree buffer
> ```
> 
> Once you're in that buffer, you should be able to navigate like usual. `tab` should fold/unfold a directory, `o` should open that file into a buffer
> 
> Then:
> 
> ```
> `n` then `f` - will prompt for a file name to create a new file
> `n` then `d` will prompt for a directory name to create a new directory
> ```

Thanks for this. Yes then thats working as expected. There are a bunch of issues with it opening in a new buffer, tab jumping to the bottom of the tree etc but all to be expected.

**Comment by mattwparas** [comment]
Yeah I'm working on a fix for that tab jumping to the end :smile:

**Comment by mattwparas** [comment]
What was the issue with it opening in a new buffer? Is it that it opens directly over the file tree rather than into a separate buffer?

**Comment by peteringram0** [comment]
* [ ] `create-file-tree` opens a new window where the tree is in a scratch buffer, additionally when running the file tree window is not active (you have to switch the window over)
* [ ] Tab goes to bottom of the tree view (as you know)
* [ ] Once selecting a file from the tree view (in left window) it will open it within the same window (as expected) but then the tree view scratch has a modification on it (from expanding the dir) so not closable without running `q!`. If using windows would be good to keep the window perminently fixed on the left (maybe at a different width) and open the buffer in the window to the right. If its supposed to not be in a window then the buffer should never be modified and should be named "tree view" or similar

I have to say though this is super cool. I will try and use it over the next few days. Would you like issues logged around this as part of this repo or is it too early at this stage?

Again thanks for your work on this!

**Comment by mattwparas** [comment]
Glad we could get it working! This comment is good enough since I'm aware of these issues. The first two points are fixable and I'm working on it, the latter point has to do with it being implemented in a buffer and dealing with the existing API, without changing it _too_ much. At the moment I think I do have it permanently open on the left side, but widths are fixed as far as I know and that hasn't changed yet


If I were to implement this in a floating window component myself, then I could mess with the width easily. Also, I do apply a custom name to the buffer (or at least I thought I did) but its possible that has bit rotted.
