### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by Boltzmachine** [mattwparas/helix-config#4]
Hi I am trying to install the plugin system and get it working. However, I got this error when I type `:fold-directory`

<img width="1184" alt="Screenshot 2024-07-10 at 1 28 32 PM" src="https://github.com/mattwparas/helix-config/assets/56542320/63f63099-8a29-4862-b55c-86257a576cd3">

**Comment by mattwparas** [comment]
Where are you running this from? Are you trying to fold a directory in the file tree, or is this just running the command standalone?

If it's just running the command on it own outside of the file tree context, this is to be expected (I can add some more error handling of course, but the expectation is it does nothing of interest)

**Comment by Boltzmachine** [comment]
Sry I thought it is the command to open the file tree, but I just found it is not
